ACADEMIC_LABEL_BLOCKLIST = {
    "economics",
    "mathematics",
    "history",
    "humanities",
    "literature",
    "sociology",
    "psychology",
    "biology",
    "chemistry",
    "physics",
    "science",
    "law",
    "philosophy",
    "english",
    "culture",
}

EDU_BLOCKLIST_SUBSTRINGS = [
    "course",
    "module",
    "student",
    "assessment",
    "assignment",
    "lecturer",
    "classroom",
    "prerequisite",
    "seminar",
    "credits",
    "term ",
    "weekly progress",
]

# Hand-built normalization rules based on module descriptions, not the job dataset.
MODULE_SKILL_RULES = [
    {"patterns": ["project", "applications", "science", "knowledge", "information", "study"], "skills": ["Research"]},
    {"patterns": ["opportunity", "business", "industry", "product", "context", "school"], "skills": ["Marketing"]},
    {"patterns": ["making", "involve", "conference", "workshops", "involved", "partners"], "skills": ["Collaboration"]},
    {"patterns": ["learn", "techniques", "guidance", "methods", "learning", "taught"], "skills": ["Learning Strategies"]},
    {"patterns": ["issues", "solving", "solutions", "solve", "challenges", "issues pertaining subject"], "skills": ["Problem Solving"]},
    {"patterns": ["communication", "discussion", "discusses", "discuss", "discussions", "sound"], "skills": ["Communication"]},
    {"patterns": ["projects", "projects approved director", "management completion", "group projects", "projects provide practical", "projects internships units"], "skills": ["Project Management"]},
    {"patterns": ["basic", "programme", "computer", "processing", "programming", "computing"], "skills": ["Programming"]},
    {"patterns": ["management", "control", "main", "role", "manage", "members"], "skills": ["Leadership"]},
    {"patterns": ["designed", "mechanics", "mechanical", "designing", "construction", "science engineering"], "skills": ["Engineering Design"]},
    {"patterns": ["future", "financial", "firm", "economic", "finance", "capital"], "skills": ["Finance"]},
    {"patterns": ["perform", "perform technical practical", "requiring perform", "performance", "improve", "techniques used"], "skills": ["Performance Practice"]},
    {"patterns": ["integrate", "integration", "functions", "function", "evaluate", "integrating"], "skills": ["Calculus"]},
    {"patterns": ["machine", "models", "selection", "model", "machine learning", "features"], "skills": ["Machine Learning"]},
    {"patterns": ["practice", "practical", "experience", "systematic", "professional", "practices"], "skills": ["Professional Practice"]},
    {"patterns": ["estimation", "statistical", "distribution", "quantitative", "statistics", "analytics"], "skills": ["Statistics"]},
    {"patterns": ["data", "analysing", "analyse", "practice data science", "data science", "analyze"], "skills": ["Data Analysis"]},
    {"patterns": ["acquire", "operations", "supply", "delivery", "production", "manufacturing"], "skills": ["Sales"]},
    {"patterns": ["study learn academic", "learn academic knowledge", "writing", "academic", "access writing", "written"], "skills": ["Academic Writing"]},
    {"patterns": ["time", "hours work", "hours work set", "number hours", "number hours work", "scheduling"], "skills": ["Time Management"]},
    {"patterns": ["department", "unit", "services", "staff", "contract", "service"], "skills": ["Customer Service"]},
    {"patterns": ["team", "activities", "group", "formation", "game", "teams"], "skills": ["Teamwork"]},
    {"patterns": ["planning", "plan", "decision making", "urban", "spatial", "roadmap"], "skills": ["Urban Planning"]},
    {"patterns": ["theory", "analytical", "mathematical", "mathematics", "rigorous", "analytic"], "skills": ["Mathematical Analysis"]},
    {"patterns": ["thinking", "critical", "critically", "think", "critically assess", "mind"], "skills": ["Critical Thinking"]},
    {"patterns": ["minimum", "objectives", "numerical", "allocation", "optimization", "nonlinear"], "skills": ["Optimization"]},
    {"patterns": ["development", "tools", "software", "developments", "practical application understanding", "application understanding"], "skills": ["Software Development"]},
    {"patterns": ["linear", "basis", "algebra", "vector", "dimensional", "vectors"], "skills": ["Linear Algebra"]},
    {"patterns": ["clinical", "medical", "treatment", "diseases", "medicine", "diagnosis"], "skills": ["Disease Management"]},
    {"patterns": ["probability", "random", "event", "markov", "events", "combinations"], "skills": ["Probability"]},
    {"patterns": ["systems", "building", "modelling", "modeling", "architecture", "landscape design"], "skills": ["Architectural Design"]},
    {"patterns": ["confidence", "intelligence", "good soft skills", "conduct", "communication skills", "soft skills"], "skills": ["Interpersonal Skills"]},
    {"patterns": ["properties", "materials", "material", "characterization", "metals", "materials science engineering"], "skills": ["Materials Characterization"]},
    {"patterns": ["evaluation", "assessed", "psychological", "assess", "examination", "tests"], "skills": ["Psychological Assessment"]},
    {"patterns": ["disciplines", "director science", "resource", "careers", "resources", "employed"], "skills": ["Human Resources"]},
    {"patterns": ["implementation", "implement", "algorithms", "algorithms technology applied", "algorithm", "implementing"], "skills": ["Algorithm Design"]},
    {"patterns": ["social", "behaviour", "society", "trends", "history", "world situations data"], "skills": ["Social Analysis"]},
    {"patterns": ["laboratory", "chemistry", "preparation science", "laboratory experiments projects", "laboratory experiments", "competencies"], "skills": ["Laboratory Skills"]},
    {"patterns": ["literature", "literature review", "interpretation", "novel", "characterisation", "interpreting"], "skills": ["Literary Analysis"]},
    {"patterns": ["perform structured", "structure", "structures", "structural", "structured", "dealing"], "skills": ["Deal Structuring"]},
    {"patterns": ["presentation", "presented", "demonstrate", "presentations", "make oral presentation", "culminates project presentation"], "skills": ["Presentation Skills"]},
    {"patterns": ["portfolio", "external investor", "investors make better", "introductory level investors", "financial investment topics", "securities analysis portfolio"], "skills": ["Investment Analysis"]},
    {"patterns": ["language", "languages", "language choice", "english", "learners"], "skills": ["Language Proficiency"]},
    {"patterns": ["solid", "solids", "solid state physics", "solid state", "atomic"], "skills": ["Solid State Physics"]},
    {"patterns": ["measures", "monitoring", "survey", "criteria", "analyses"], "skills": ["Statistical Analysis"]},
    {"patterns": ["environment", "environmental", "sustainable", "sustainability"], "skills": ["Sustainable Design"]},
    {"patterns": ["health", "economics", "healthcare", "insurance"], "skills": ["Health Economics"]},
    {"patterns": ["legal", "media", "laws", "second law"], "skills": ["Media Law"]},
    {"patterns": ["select", "entries", "selecting", "tables"], "skills": ["SQL"]},
    {"patterns": ["regulation", "regulatory", "policies", "regulators"], "skills": ["Financial Regulation"]},
    {"patterns": ["perspective financial reporting", "aware financial statements", "financial analysts cfa", "quantitative analysis equity"], "skills": ["Financial Analysis"]},
    {"patterns": ["introduction accounting user", "investor focus accounting", "productivity", "accounting"], "skills": ["Accounting"]},
    {"patterns": ["quality", "reliability", "assurance"], "skills": ["Quality Assurance"]},
    {"patterns": ["risk", "safety", "security"], "skills": ["Risk Management"]},
    {"patterns": ["generation", "develops", "development life cycle"], "skills": ["Child Development"]},
    {"patterns": ["corporate", "industry government bodies", "organisations companies vetted"], "skills": ["Corporate Governance"]},
    {"patterns": ["chain", "supply chain management", "inventory"], "skills": ["Supply Chain Management"]},
    {"patterns": ["visual", "graphs", "graph"], "skills": ["Data Visualization"]},
    {"patterns": ["computing database", "information systems", "analytics management"], "skills": ["Database Management"]},
    {"patterns": ["wave", "waves", "signal processing"], "skills": ["Wave Analysis"]},
    {"patterns": ["deeds giving free", "estate"], "skills": ["Charity Law"]},
    {"patterns": ["physics", "optical"], "skills": ["Optical Physics"]},
    {"patterns": ["relationship", "relationships"], "skills": ["Customer Relationship Management"]},
    {"patterns": ["python", "learning python"], "skills": ["Python"]},
    {"patterns": ["mining", "clustering"], "skills": ["Data Mining"]},
    {"patterns": ["risks", "benefits risks having"], "skills": ["Risk Analysis"]},
    {"patterns": ["electronics", "semiconductor"], "skills": ["Semiconductor Fundamentals"]},
    {"patterns": ["world policy", "political"], "skills": ["Political Analysis"]},
    {"patterns": ["management factors socio", "socio"], "skills": ["Sociolegal Analysis"]},
]

PRACTICAL_ANCHORS = [
    "analysis",
    "analytics",
    "algebra",
    "calculus",
    "probability",
    "statistics",
    "regression",
    "optimization",
    "programming",
    "python",
    "database",
    "sql",
    "machine learning",
    "data mining",
    "visualization",
    "visualisation",
    "regulation",
    "governance",
    "banking",
    "finance",
    "investment",
    "design",
    "engineering",
    "semiconductor",
    "photovoltaic",
    "solar",
    "research",
    "writing",
    "presentation",
    "collaboration",
    "performance",
]

EXPLICIT_PHRASE_BLOCKLIST = {
    "analysis",
    "design",
    "engineering",
    "writing",
    "performance",
    "regression",
    "analytics",
    "investment",
    "research projects",
    "select research topics",
    "conducting research",
    "engineering principles",
    "real analysis",
    "algebra",
}

CANONICAL_MODULE_SKILLS = [
    "Academic Writing",
    "Accounting",
    "Algorithm Design",
    "Architectural Design",
    "Calculus",
    "Charity Law",
    "Child Development",
    "Collaboration",
    "Communication",
    "Corporate Governance",
    "Critical Thinking",
    "Customer Relationship Management",
    "Customer Service",
    "Data Analysis",
    "Data Mining",
    "Data Visualization",
    "Database Management",
    "Deal Structuring",
    "Disease Management",
    "Engineering Design",
    "Finance",
    "Financial Analysis",
    "Financial Regulation",
    "Health Economics",
    "Human Resources",
    "Interpersonal Skills",
    "Investment Analysis",
    "Laboratory Skills",
    "Language Proficiency",
    "Leadership",
    "Learning Strategies",
    "Linear Algebra",
    "Literary Analysis",
    "Machine Learning",
    "Marketing",
    "Materials Characterization",
    "Mathematical Analysis",
    "Media Law",
    "Optical Physics",
    "Optimization",
    "Performance Practice",
    "Political Analysis",
    "Presentation Skills",
    "Probability",
    "Problem Solving",
    "Professional Practice",
    "Programming",
    "Project Management",
    "Psychological Assessment",
    "Python",
    "Quality Assurance",
    "Research",
    "Risk Analysis",
    "Risk Management",
    "SQL",
    "Sales",
    "Semiconductor Fundamentals",
    "Social Analysis",
    "Sociolegal Analysis",
    "Software Development",
    "Solid State Physics",
    "Statistical Analysis",
    "Statistics",
    "Supply Chain Management",
    "Sustainable Design",
    "Teamwork",
    "Time Management",
    "Urban Planning",
    "Wave Analysis",
]

STRICT_CANONICAL_EVIDENCE = {
    "Urban Planning": ["urban", "city planning", "urban planning", "urban design", "master planners"],
    "Media Law": ["entertainment law", "media regulation", "celebrity rights", "broadcast law", "defamation"],
    "Learning Strategies": ["learning to learn", "study skills", "learning strategies", "evidence-based techniques for learning"],
}
