ACADEMIC_LABEL_BLOCKLIST = {
    "economics",
    "mathematics",
    "history",
    "humanities",
    "literature",
    "sociology",
    "psychology",
    "biology",
    "chemistry",
    "physics",
    "science",
    "law",
    "philosophy",
    "english",
    "culture",
}

EDU_BLOCKLIST_SUBSTRINGS = [
    "course",
    "module",
    "student",
    "assessment",
    "assignment",
    "lecturer",
    "classroom",
    "prerequisite",
    "seminar",
    "credits",
    "term ",
    "weekly progress",
]

# Hand-built normalization rules based on module descriptions, not the job dataset.
MODULE_SKILL_RULES = [
    {"patterns": ["project", "applications", "science", "knowledge", "information", "study"], "skills": ["Research"]},
    {"patterns": ["opportunity", "business", "industry", "context", "product", "innovation"], "skills": ["Marketing"]},
    {"patterns": ["making", "conference", "workshops", "involve", "involved", "independently"], "skills": ["Collaboration"]},
    {"patterns": ["issues", "solving", "solutions", "solve", "challenges", "issues pertaining subject"], "skills": ["Problem Solving"]},
    {"patterns": ["learn", "techniques", "methods", "learning", "guidance", "taught"], "skills": ["Learning Strategies"]},
    {"patterns": ["basic", "programme", "computer", "processing", "computing", "programming"], "skills": ["Programming"]},
    {"patterns": ["management", "control", "main", "role", "discipline", "members"], "skills": ["Leadership"]},
    {"patterns": ["communication", "discuss", "discussions", "communicating", "interactions", "signal"], "skills": ["Communication"]},
    {"patterns": ["designed", "mechanics", "mechanical", "construction", "science engineering", "based design"], "skills": ["Engineering Design"]},
    {"patterns": ["integration", "integrate", "functions", "function", "evaluate", "integrating"], "skills": ["Calculus"]},
    {"patterns": ["projects", "projects provide practical", "completion project assist", "long project", "project management", "projects provide"], "skills": ["Project Management"]},
    {"patterns": ["machine", "models", "selection", "model", "machine learning", "features"], "skills": ["Machine Learning"]},
    {"patterns": ["estimation", "statistical", "population", "distribution", "quantitative", "statistics"], "skills": ["Statistics"]},
    {"patterns": ["acquire", "operations", "supply", "delivery", "manufacturing", "acquired"], "skills": ["Sales"]},
    {"patterns": ["data", "analysing", "analyse", "practice data science", "data science", "analyze"], "skills": ["Data Analysis"]},
    {"patterns": ["practice", "practical", "experience", "systematic", "practices", "professional"], "skills": ["Professional Practice"]},
    {"patterns": ["perform", "perform technical practical", "requiring perform", "performance", "improve", "techniques used"], "skills": ["Performance Practice"]},
    {"patterns": ["study learn academic", "learn academic knowledge", "writing", "access writing", "written", "academic"], "skills": ["Academic Writing"]},
    {"patterns": ["future", "economic", "financial", "rich", "capital", "finance"], "skills": ["Finance"]},
    {"patterns": ["clinical", "medical", "treatment", "diseases", "medicine", "diagnosis"], "skills": ["Disease Management"]},
    {"patterns": ["theory", "mathematical", "analytical", "analytic", "mathematics", "rigorous"], "skills": ["Mathematical Analysis"]},
    {"patterns": ["linear", "basis", "algebra", "vector", "dimensional", "vectors"], "skills": ["Linear Algebra"]},
    {"patterns": ["social", "society", "behaviour", "history", "trends", "world situations data"], "skills": ["Social Analysis"]},
    {"patterns": ["numerical", "optimization", "objectives", "minimum", "allocation", "heuristic"], "skills": ["Optimization"]},
    {"patterns": ["systems", "building", "modelling", "modeling", "architecture", "landscape design"], "skills": ["Architectural Design"]},
    {"patterns": ["development", "tools", "software", "developments", "practical application understanding", "software engineering"], "skills": ["Software Development"]},
    {"patterns": ["properties", "materials", "material", "metals", "characterization", "physical chemical"], "skills": ["Materials Characterization"]},
    {"patterns": ["team", "activities", "group", "formation", "teams", "progress"], "skills": ["Teamwork"]},
    {"patterns": ["department", "staff", "unit", "services", "maintenance", "service"], "skills": ["Customer Service"]},
    {"patterns": ["implementation", "algorithms", "algorithms technology applied", "implement", "algorithm", "implementing"], "skills": ["Algorithm Design"]},
    {"patterns": ["planning", "decision making", "urban", "plan", "city", "spatial"], "skills": ["Urban Planning"]},
    {"patterns": ["thinking", "critical", "critically", "think", "critical thinking", "thought process"], "skills": ["Critical Thinking"]},
    {"patterns": ["confidence", "intelligence", "good soft skills", "conduct", "communication skills", "knowledge skills aptitudes"], "skills": ["Interpersonal Skills"]},
    {"patterns": ["evaluation", "assess", "psychological", "assessed", "evaluating", "competence analysing"], "skills": ["Psychological Assessment"]},
    {"patterns": ["disciplines", "resources", "resource", "staff department", "actual working environment", "employed"], "skills": ["Human Resources"]},
    {"patterns": ["literature", "literature review", "interpretation", "characterisation", "novel", "interpreting"], "skills": ["Literary Analysis"]},
    {"patterns": ["perform structured", "structure", "structures", "structural", "structured", "dealing"], "skills": ["Deal Structuring"]},
    {"patterns": ["time", "scheduling", "times", "participate time", "time month", "participate time month"], "skills": ["Time Management"]},
    {"patterns": ["probability", "random", "event", "markov", "uncertainty", "conditional"], "skills": ["Probability"]},
    {"patterns": ["laboratory", "chemistry", "laboratory experiments projects", "laboratory experiments", "competencies"], "skills": ["Laboratory Skills"]},
    {"patterns": ["presentation", "presented", "demonstrate", "presentations", "culminates project presentation"], "skills": ["Presentation Skills"]},
    {"patterns": ["environment", "environmental", "sustainable", "sustainability"], "skills": ["Sustainable Design"]},
    {"patterns": ["health", "economics", "healthcare", "economics topics covered"], "skills": ["Health Economics"]},
    {"patterns": ["language", "languages", "language choice", "learners"], "skills": ["Language Proficiency"]},
    {"patterns": ["legal", "laws", "media", "second law"], "skills": ["Media Law"]},
    {"patterns": ["monitoring", "analyses", "measures", "criteria"], "skills": ["Statistical Analysis"]},
    {"patterns": ["solid", "solids", "atomic"], "skills": ["Solid State Physics"]},
    {"patterns": ["risk", "safety", "security"], "skills": ["Risk Management"]},
    {"patterns": ["generation", "develops", "development life cycle"], "skills": ["Child Development"]},
    {"patterns": ["chain", "supply chain management", "inventory"], "skills": ["Supply Chain Management"]},
    {"patterns": ["policies", "regulation", "regulatory"], "skills": ["Financial Regulation"]},
    {"patterns": ["visual", "graphs", "graph"], "skills": ["Data Visualization"]},
    {"patterns": ["quality", "reliability"], "skills": ["Quality Assurance"]},
    {"patterns": ["physics", "optical"], "skills": ["Optical Physics"]},
    {"patterns": ["relationship", "relationships"], "skills": ["Customer Relationship Management"]},
    {"patterns": ["select", "selecting"], "skills": ["SQL"]},
    {"patterns": ["python", "learning python"], "skills": ["Python"]},
    {"patterns": ["mining", "clustering"], "skills": ["Data Mining"]},
    {"patterns": ["electronics", "semiconductor"], "skills": ["Semiconductor Fundamentals"]},
]

PRACTICAL_ANCHORS = [
    "analysis",
    "analytics",
    "algebra",
    "calculus",
    "probability",
    "statistics",
    "regression",
    "optimization",
    "programming",
    "python",
    "database",
    "sql",
    "machine learning",
    "data mining",
    "visualization",
    "visualisation",
    "regulation",
    "governance",
    "banking",
    "finance",
    "investment",
    "design",
    "engineering",
    "semiconductor",
    "photovoltaic",
    "solar",
    "research",
    "writing",
    "presentation",
    "collaboration",
    "performance",
]

EXPLICIT_PHRASE_BLOCKLIST = {
    "analysis",
    "design",
    "engineering",
    "writing",
    "performance",
    "regression",
    "analytics",
    "investment",
    "research projects",
    "select research topics",
    "conducting research",
    "engineering principles",
    "real analysis",
    "algebra",
}

CANONICAL_MODULE_SKILLS = [
    "Academic Writing",
    "Algorithm Design",
    "Architectural Design",
    "Calculus",
    "Child Development",
    "Collaboration",
    "Communication",
    "Critical Thinking",
    "Customer Relationship Management",
    "Customer Service",
    "Data Analysis",
    "Data Mining",
    "Data Visualization",
    "Deal Structuring",
    "Disease Management",
    "Engineering Design",
    "Finance",
    "Financial Regulation",
    "Health Economics",
    "Human Resources",
    "Interpersonal Skills",
    "Laboratory Skills",
    "Language Proficiency",
    "Leadership",
    "Learning Strategies",
    "Linear Algebra",
    "Literary Analysis",
    "Machine Learning",
    "Marketing",
    "Materials Characterization",
    "Mathematical Analysis",
    "Media Law",
    "Optical Physics",
    "Optimization",
    "Performance Practice",
    "Presentation Skills",
    "Probability",
    "Problem Solving",
    "Professional Practice",
    "Programming",
    "Project Management",
    "Psychological Assessment",
    "Python",
    "Quality Assurance",
    "Research",
    "Risk Management",
    "SQL",
    "Sales",
    "Semiconductor Fundamentals",
    "Social Analysis",
    "Software Development",
    "Solid State Physics",
    "Statistical Analysis",
    "Statistics",
    "Supply Chain Management",
    "Sustainable Design",
    "Teamwork",
    "Time Management",
    "Urban Planning",
]

STRICT_CANONICAL_EVIDENCE = {
    "Urban Planning": ["urban", "city planning", "urban planning", "urban design", "master planners"],
    "Media Law": ["entertainment law", "media regulation", "celebrity rights", "broadcast law", "defamation"],
    "Learning Strategies": ["learning to learn", "study skills", "learning strategies", "evidence-based techniques for learning"],
}
