ACADEMIC_LABEL_BLOCKLIST = {
    "economics",
    "mathematics",
    "history",
    "humanities",
    "literature",
    "sociology",
    "psychology",
    "biology",
    "chemistry",
    "physics",
    "science",
    "law",
    "philosophy",
    "english",
    "culture",
}

EDU_BLOCKLIST_SUBSTRINGS = [
    "course",
    "module",
    "student",
    "assessment",
    "assignment",
    "lecturer",
    "classroom",
    "prerequisite",
    "seminar",
    "credits",
    "term ",
    "weekly progress",
]

# Hand-built normalization rules based on module descriptions, not the job dataset.
MODULE_SKILL_RULES = [
    {"patterns": ["linear algebra", "matrix algebra"], "skills": ["Linear Algebra"]},
    {"patterns": ["probability theory", "probability", "stochastic"], "skills": ["Probability"]},
    {"patterns": ["multivariate calculus", "calculus", "differentiation", "integration"], "skills": ["Calculus"]},
    {"patterns": ["constrained optimisation", "constrained optimization", "optimization", "optimisation"], "skills": ["Optimization"]},
    {"patterns": ["real analysis"], "skills": ["Mathematical Analysis"]},
    {"patterns": ["econometrics", "regression", "time series"], "skills": ["Econometrics", "Regression Analysis"]},
    {"patterns": ["statistical inference", "hypothesis testing", "statistics", "statistical"], "skills": ["Statistical Analysis"]},
    {"patterns": ["data analysis", "data analyses", "analytical approach", "analytics"], "skills": ["Data Analysis"]},
    {"patterns": ["machine learning", "supervised learning", "unsupervised learning", "reinforcement learning"], "skills": ["Machine Learning"]},
    {"patterns": ["data mining", "pattern mining"], "skills": ["Data Mining"]},
    {"patterns": ["programming language", "programming", "coding"], "skills": ["Programming"]},
    {"patterns": ["python"], "skills": ["Python"]},
    {"patterns": ["software development", "software engineering"], "skills": ["Software Development"]},
    {"patterns": ["algorithm", "algorithms"], "skills": ["Algorithm Design"]},
    {"patterns": ["database", "databases", "relational database"], "skills": ["Database Management"]},
    {"patterns": ["sql"], "skills": ["SQL"]},
    {"patterns": ["data visualisation", "data visualization", "visual analytics"], "skills": ["Data Visualization"]},
    {"patterns": ["financial regulation", "regulation of financial", "regulatory"], "skills": ["Financial Regulation"]},
    {"patterns": ["financial markets", "financial products", "financial services"], "skills": ["Financial Analysis"]},
    {"patterns": ["financial stability", "risk"], "skills": ["Risk Analysis"]},
    {"patterns": ["corporate governance"], "skills": ["Corporate Governance"]},
    {"patterns": ["central banks", "central banking", "monetary policy"], "skills": ["Banking"]},
    {"patterns": ["private equity", "venture capital", "hedge fund", "alternative investments"], "skills": ["Investment Analysis"]},
    {"patterns": ["green buildings", "green building"], "skills": ["Sustainable Design"]},
    {"patterns": ["architecture", "building process"], "skills": ["Architectural Design"]},
    {"patterns": ["engineering principles", "engineering design"], "skills": ["Engineering Design"]},
    {"patterns": ["solar photovoltaic", "solar pv", "solar cells"], "skills": ["Solar PV"]},
    {"patterns": ["semiconductors", "semiconductor"], "skills": ["Semiconductor Fundamentals"]},
    {"patterns": ["performance", "ensemble playing", "studio class"], "skills": ["Performance Practice"]},
    {"patterns": ["research topics", "conducting research", "research"], "skills": ["Research"]},
    {"patterns": ["thesis", "scientific writing", "report writing"], "skills": ["Academic Writing"]},
    {"patterns": ["oral presentation", "present findings", "presentation"], "skills": ["Presentation Skills"]},
    {"patterns": ["group work", "assigned groups", "collaboration", "collaborative"], "skills": ["Collaboration"]},
    {"patterns": ["critical thinking", "reasoning", "decision making"], "skills": ["Critical Thinking"]},
    {"patterns": ["problem solving"], "skills": ["Problem Solving"]},
    {"patterns": ["diagnostic classification", "psychological problems", "psychopathology"], "skills": ["Psychological Assessment"]},
    {"patterns": ["adult psychological", "adult psychopathology"], "skills": ["Mental Health Assessment"]},
    {"patterns": ["arabic alphabet", "basic vocabulary", "communicative situations"], "skills": ["Language Proficiency"]},
    {"patterns": ["child development", "developmental theories", "early childhood"], "skills": ["Child Development"]},
    {"patterns": ["internship", "industrial attachment", "professional placement", "work experience"], "skills": ["Professional Practice"]},
    {"patterns": ["laboratory class", "hands on experiments", "experiments"], "skills": ["Laboratory Skills"]},
    {"patterns": ["materials properties", "mechanical properties", "chemical properties", "electrical properties"], "skills": ["Materials Characterization"]},
    {"patterns": ["rhetoric", "stylistic features"], "skills": ["Rhetorical Analysis"]},
    {"patterns": ["transactional lawyer", "architect deals", "private orderings"], "skills": ["Deal Structuring"]},
    {"patterns": ["retinal", "posterior eye", "ophthalmology", "ocular"], "skills": ["Ophthalmology"]},
    {"patterns": ["common retinal diseases", "disease management", "co-managing"], "skills": ["Disease Management"]},
    {"patterns": ["solid state", "crystalline solids", "energy bands", "fermi surfaces"], "skills": ["Solid State Physics"]},
    {"patterns": ["optical processes", "plasmons", "polaritons", "polarons"], "skills": ["Optical Physics"]},
    {"patterns": ["language as interaction", "interactional", "communication"], "skills": ["Communication Analysis"]},
    {"patterns": ["literary trends", "literary genre", "literature"], "skills": ["Literary Analysis"]},
    {"patterns": ["politics", "political regimes", "inter-korean relations"], "skills": ["Political Analysis"]},
    {"patterns": ["ethnicity", "ethnic relations", "nation-state"], "skills": ["Social Analysis"]},
    {"patterns": ["light and sound", "waves", "rainbow"], "skills": ["Wave Analysis"]},
    {"patterns": ["intellectual property", "copyright", "trade mark", "trademark", "patent"], "skills": ["Intellectual Property Law"]},
    {"patterns": ["arbitration", "international court of arbitration", "dispute resolution"], "skills": ["Arbitration"]},
    {"patterns": ["taxation", "income tax", "double taxation"], "skills": ["Tax Law"]},
    {"patterns": ["charity law", "charity status"], "skills": ["Charity Law"]},
    {"patterns": ["data privacy", "privacy law", "personal information"], "skills": ["Data Privacy Law"]},
    {"patterns": ["entertainment law", "media regulation", "celebrity rights", "broadcast law", "defamation"], "skills": ["Media Law"]},
    {"patterns": ["law and society", "justice and society", "urbanization", "industrialization"], "skills": ["Sociolegal Analysis"]},
    {"patterns": ["cross-border transactions", "global economy", "businesses operating"], "skills": ["International Taxation"]},
    {"patterns": ["brand management", "strong brand", "brand"], "skills": ["Brand Management"]},
    {"patterns": ["market validation", "entrepreneurship", "innovation"], "skills": ["Market Validation"]},
    {"patterns": ["computer aided design", "3d cad", "prototyping"], "skills": ["CAD Prototyping"]},
    {"patterns": ["urban systems", "master planners", "urban planning", "city planning", "urban design"], "skills": ["Urban Planning"]},
    {"patterns": ["enhanced oil recovery", "porous media", "sweep efficiency"], "skills": ["Reservoir Engineering"]},
    {"patterns": ["industrial wastewater", "wastewater treatment", "heavy metal ions"], "skills": ["Wastewater Treatment"]},
    {"patterns": ["customer relationship management", "winning back customers", "retaining"], "skills": ["Customer Relationship Management"]},
    {"patterns": ["pharmacoeconomics", "drug pricing", "reimbursement", "market access"], "skills": ["Health Economics"]},
    {"patterns": ["learning to learn", "evidence-based techniques for learning"], "skills": ["Learning Strategies"]},
]

PRACTICAL_ANCHORS = [
    "analysis",
    "analytics",
    "algebra",
    "calculus",
    "probability",
    "statistics",
    "regression",
    "optimization",
    "programming",
    "python",
    "database",
    "sql",
    "machine learning",
    "data mining",
    "visualization",
    "visualisation",
    "regulation",
    "governance",
    "banking",
    "finance",
    "investment",
    "design",
    "engineering",
    "semiconductor",
    "photovoltaic",
    "solar",
    "research",
    "writing",
    "presentation",
    "collaboration",
    "performance",
]

EXPLICIT_PHRASE_BLOCKLIST = {
    "analysis",
    "design",
    "engineering",
    "writing",
    "performance",
    "regression",
    "analytics",
    "investment",
    "research projects",
    "select research topics",
    "conducting research",
    "engineering principles",
    "real analysis",
    "algebra",
}

CANONICAL_MODULE_SKILLS = [
    "Academic Writing",
    "Algorithm Design",
    "Architectural Design",
    "Banking",
    "Calculus",
    "Child Development",
    "Collaboration",
    "Communication Analysis",
    "Corporate Governance",
    "Customer Relationship Management",
    "Critical Thinking",
    "CAD Prototyping",
    "Data Analysis",
    "Data Privacy Law",
    "Data Mining",
    "Data Visualization",
    "Database Management",
    "Deal Structuring",
    "Disease Management",
    "Econometrics",
    "Engineering Design",
    "Financial Analysis",
    "Financial Regulation",
    "Health Economics",
    "Intellectual Property Law",
    "International Taxation",
    "Investment Analysis",
    "Language Proficiency",
    "Laboratory Skills",
    "Learning Strategies",
    "Linear Algebra",
    "Literary Analysis",
    "Market Validation",
    "Media Law",
    "Machine Learning",
    "Materials Characterization",
    "Mathematical Analysis",
    "Mental Health Assessment",
    "Ophthalmology",
    "Optimization",
    "Optical Physics",
    "Performance Practice",
    "Political Analysis",
    "Presentation Skills",
    "Probability",
    "Problem Solving",
    "Professional Practice",
    "Programming",
    "Psychological Assessment",
    "Python",
    "Arbitration",
    "Research",
    "Regression Analysis",
    "Reservoir Engineering",
    "Rhetorical Analysis",
    "Risk Analysis",
    "Semiconductor Fundamentals",
    "Sociolegal Analysis",
    "Social Analysis",
    "Software Development",
    "Solid State Physics",
    "Solar PV",
    "SQL",
    "Statistical Analysis",
    "Sustainable Design",
    "Tax Law",
    "Urban Planning",
    "Wave Analysis",
    "Wastewater Treatment",
    "Brand Management",
    "Charity Law",
]

STRICT_CANONICAL_EVIDENCE = {
    "Urban Planning": ["urban", "city planning", "urban planning", "urban design", "master planners"],
    "Media Law": ["entertainment law", "media regulation", "celebrity rights", "broadcast law", "defamation"],
    "Learning Strategies": ["learning to learn", "study skills", "learning strategies", "evidence-based techniques for learning"],
}
